apiVersion: v1
kind: Service
metadata:
  name: tcp-lb-onearm
  namespace: apps
  annotations:
    loxilb.io/liveness: "yes"
    loxilb.io/lbmode: "onearm"
    loxilb.io/staticIP: "10.1.3.1"
spec:
  externalTrafficPolicy: Local
  loadBalancerClass: loxilb.io/loxilb
  selector:
    what: tcp-onearm-test
  ports:
    - port: 55002
      targetPort: 80
  type: LoadBalancer