apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: example-preflight
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
  analyzers:
    - clusterVersion:
        outcomes:
          - fail:
              when: "< 1.22.0"
              message: "Kubernetes version must be at least 1.22.0"
          - pass:
              message: "Kubernetes version is sufficient"
